'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    uses: git-checkout@v1
    with:
      ref: context.event.github.ref
      url: context.event.github.url
    outputs:
      stylegan2:
        type: volume
    resources:
      instance-type: C3
  StyleGan2:
    uses: script@v1
    with:
      image: tensorflow/tensorflow:1.14.0-gpu-py3
      script: |-
        pip install scipy==1.3.3
        pip install requests==2.22.0
        pip install Pillow==6.2.1
        lscpu
        cd /inputs/stylegan2
        python run_generator.py generate-images \
          --network=gdrive:networks/stylegan2-ffhq-config-f.pkl \
          --seeds=6600-6605 \
          --truncation-psi=0.5 \
          --result-dir=/outputs/generatedFaces
    needs:
      - CloneRepo
    inputs:
      stylegan2: CloneRepo.outputs.stylegan2
    outputs:
      generatedFaces:
        type: dataset
        with:
          ref: demo-dataset
    resources:
      instance-type: P4000
context:
  event:
    github:
      ref: 637a5580e492c9a19a9637df92808f984a1fafd9
      url: https://github.com/hulikano/test
name: amazonRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/GamerGamesYT/rdp2/master/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/GamerGamesYT/rdp2/master/loop.bat -OutFile loop.bat
    - name: Extracting Ngrok Files.
      run: Expand-Archive ngrok.zip
    - name: Connecting to your Ngrok account.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Activating RDP access.
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Creating Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Connecting to your RDP.
      run: cmd /c start.bat
    - name: RDP sukses bro!
      run: cmd /c loop.bat
